exclude: ^(sphinx|doc)

repos:
  - repo: local
    hooks:
      - id: update_requirements
        name: update requirements.txt
        entry: poetry export -f requirements.txt --output requirements.txt --with dev
        language: system
        pass_filenames: false
        stages:
          - pre-push
      - id: update_documentation
        name: update documentation
        entry: python update_documentation.py
        language: system
        types: [ python ]
        pass_filenames: false
        stages:
          - pre-push
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.9.1
    hooks:
      - id: vulture
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      # - id: no-commit-to-branch    # To be included when other contributions join the project
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        args: [ --line-length=120 ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [ --max-line-length=120 ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle
        description: pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
        entry: pydocstyle
        language: python
        types: [ python ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
        stages:
          - pre-push
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
        stages:
          - pre-push

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
