repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        args: [ --line-length=120 ]
        exclude: ^(docs/)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle
        description: pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
        entry: pydocstyle
        language: python
        types: [ python ]
