minimum_pre_commit_version: "3.4.0"
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]
exclude: ^(?:docs|sphinx)/

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.5"
    hooks:
      - id: poetry-check
        stages: [pre-push]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest json2graph/tests/test_main.py
        language: system
        pass_filenames: false
        files: ^(?:json2graph/.*|pyproject\.toml|poetry\.lock|requirements\.txt)$
        stages: [pre-push]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-ast
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.8.0
    hooks:
      - id: poetry-export
        additional_dependencies: [poetry==1.8.5, poetry-core==1.9.1]
        args: [-f, requirements.txt, -o, requirements.txt, --with, dev]
        files: ^(?:pyproject\.toml|poetry\.lock)$

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
